/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get list of all active agents */
        get: operations["Agents_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a specific agent by ID */
        get: operations["Agents_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Agent information representing a Claude agent process */
        Agent: {
            /** @description Unique identifier (UUID) for the agent */
            id: string;
            /**
             * Format: int32
             * @description Process ID of the agent
             */
            pid: number;
            /** @description Session ID of the Claude session */
            sessionId: string;
            /** @description Project directory path */
            projectDir: string;
            /** @description Project name (extracted from projectDir) */
            projectName: string;
            /** @description Type of the agent (e.g., "Claude Code") */
            agentType: string;
            /**
             * Format: date-time
             * @description Timestamp when the agent was created
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the agent was last updated
             */
            updatedAt: string;
            /** @description Session details */
            session?: components["schemas"]["Session"];
        };
        /** @description Response containing a list of agents */
        AgentListResponse: {
            /** @description List of active agents */
            agents: components["schemas"]["Agent"][];
        };
        /** @description Background task information */
        BackgroundTaskInfo: {
            /** @description Background task ID */
            backgroundTaskId: string;
            /** @description Tool use ID associated with this task */
            toolUseId: string;
            /** @description Command being executed */
            command: string;
            /** @description Description of the task */
            description: string;
            /** @description Whether the task has been terminated */
            isTerminated: boolean;
            /**
             * Format: date-time
             * @description Timestamp when the task was created
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the task was terminated
             */
            terminatedAt?: string;
        };
        /** @description Chat message sent via WebSocket */
        ChatMessage: {
            /** @description Unique message ID */
            id: string;
            /** @description Type of the message */
            type: components["schemas"]["MessageType"];
            /**
             * @description Role of the message sender
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /**
             * @description Sub-type for assistant messages
             * @enum {string}
             */
            subType?: "audio" | "text";
            /** @description Text content of the message */
            text: string;
            /** @description Base64 encoded audio data (WAV format) */
            audioData?: string;
            /**
             * Format: int32
             * @description Priority for audio playback (higher = higher priority)
             * @default 50
             */
            priority: number;
            /**
             * Format: date-time
             * @description Timestamp of the message
             */
            timestamp: string;
            /** @description Message metadata */
            metadata?: components["schemas"]["MessageMetadata"];
            /** @description Tool name (for tool_use messages) */
            toolName?: string;
            /** @description Tool input (for tool_use messages) */
            toolInput?: {
                [key: string]: unknown;
            };
            /** @description Tool result output (for tool_result messages) */
            toolOutput?: string;
            /** @description Error details (for error messages) */
            error?: string;
            /** @description Content details (for content_block messages) */
            content?: string;
        };
        /** @description Client message sent to WebSocket */
        ClientMessage: {
            /** @description Message type */
            type: components["schemas"]["MessageType"];
            /** @description Session ID for the message */
            sessionId?: string;
            /** @description Text content (for user_message) */
            text?: string;
            /**
             * @description Action for confirm_response
             * @enum {string}
             */
            action?: "permit" | "deny";
            /** @description Message ID for confirm_response */
            messageId?: string;
            /** @description State for update_state */
            state?: components["schemas"]["WebSocketConnectionState"];
            /**
             * Format: date-time
             * @description Timestamp
             */
            timestamp: string;
        };
        /**
         * @description Connection status for WebSocket
         * @enum {string}
         */
        ConnectionStatus: "connecting" | "connected" | "disconnected" | "error" | "failed";
        /** @description Error response */
        ErrorResponse: {
            /** @description Error message */
            message: string;
        };
        /** @description Message metadata */
        MessageMetadata: {
            /** @description Event type */
            eventType: string;
            /** @description Tool name */
            toolName?: string;
            /**
             * Format: int32
             * @description Speaker number
             */
            speaker?: number;
            /**
             * Format: int32
             * @description Sample rate for audio
             */
            sampleRate?: number;
            /**
             * Format: float
             * @description Duration in seconds
             */
            duration?: number;
            /** @description Session ID */
            sessionId?: string;
            /**
             * Format: int32
             * @description Agent ID (PID) associated with this message
             */
            agentId?: number;
            /**
             * @description Role of the message
             * @enum {string}
             */
            role?: "user" | "assistant" | "system";
            /**
             * @description Sub-type for assistant messages
             * @enum {string}
             */
            subType?: "audio" | "text";
        };
        /**
         * @description WebSocket message types
         * @enum {string}
         */
        MessageType: "user" | "assistant" | "system" | "notification" | "audio" | "text" | "ping" | "pong" | "user_message" | "confirm_response" | "update_state" | "tool_use" | "tool_result" | "content_block" | "error";
        /** @description Session information */
        Session: {
            /** @description Session ID */
            sessionId: string;
            /** @description UUID of the event that created this session */
            uuid: string;
            /** @description Current working directory */
            cwd: string;
            /** @description Path to the transcript file */
            transcriptPath: string;
            /**
             * Format: date-time
             * @description Timestamp when the session started
             */
            startTime: string;
            /** @description Active tool information */
            activeTool?: components["schemas"]["ToolInfo"];
            /** @description Background tasks */
            backgroundTasks?: components["schemas"]["BackgroundTaskInfo"][];
            /** @description Active tasks */
            activeTasks?: components["schemas"]["TaskInfo"][];
        };
        /** @description Task information */
        TaskInfo: {
            /** @description Task ID */
            taskId: string;
            /** @description Tool use ID associated with this task */
            toolUseId: string;
            /** @description Task name */
            taskName: string;
            /** @description Description of the task */
            description: string;
            /**
             * @description Task status
             * @enum {string}
             */
            status: "pending" | "in_progress" | "completed";
            /**
             * Format: date-time
             * @description Timestamp when the task was created
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the task was last updated
             */
            updatedAt: string;
        };
        /** @description Tool execution information */
        ToolInfo: {
            /** @description Tool use ID */
            toolUseId: string;
            /** @description Tool name */
            toolName: string;
            /** @description Tool status */
            status: components["schemas"]["ToolStatus"];
            /**
             * Format: date-time
             * @description Timestamp when the tool was created
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the tool was last updated
             */
            updatedAt: string;
            /** @description Whether the tool resulted in an error */
            isError: boolean;
            /** @description Whether the tool was rejected */
            isRejected: boolean;
            /** @description Whether the tool is waiting for approval */
            isWaitingApproval: boolean;
        };
        /**
         * @description Tool execution status
         * @enum {string}
         */
        ToolStatus: "created" | "finished";
        /** @description WebSocket connection state */
        WebSocketConnectionState: {
            /**
             * @description Connection mode
             * @enum {string}
             */
            mode: "timeline" | "agent";
            /**
             * Format: int32
             * @description Agent PID when in agent mode
             */
            agentPid?: number;
        };
        /** @description WebSocket status message */
        WebSocketStatus: {
            /** @description Current connection status */
            status: components["schemas"]["ConnectionStatus"];
            /** @description Optional error message */
            error?: string;
            /**
             * Format: date-time
             * @description Timestamp of status change
             */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Agents_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentListResponse"];
                };
            };
        };
    };
    Agents_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
