/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get list of all active agents */
        get: operations["Agents_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a specific agent by PID */
        get: operations["Agents_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Agent information representing a Claude agent process */
        Agent: {
            /**
             * Format: int32
             * @description Process ID of the agent
             */
            pid: number;
            /** @description Session ID of the Claude session */
            sessionId: string;
            /** @description Project directory path */
            projectDir: string;
            /** @description Project name (extracted from projectDir) */
            projectName: string;
            /**
             * Format: date-time
             * @description Timestamp when the agent was created
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the agent was last updated
             */
            updatedAt: string;
        };
        /** @description Response containing a list of agents */
        AgentListResponse: {
            /** @description List of active agents */
            agents: components["schemas"]["Agent"][];
        };
        /** @description Chat message sent via WebSocket */
        ChatMessage: {
            /** @description Unique message ID */
            id?: string;
            /** @description Type of the message */
            type: components["schemas"]["MessageType"];
            /**
             * @description Role of the message sender
             * @enum {string}
             */
            role?: "user" | "assistant" | "system";
            /**
             * @description Sub-type for assistant messages
             * @enum {string}
             */
            subType?: "audio" | "text";
            /** @description Text content of the message */
            text?: string;
            /** @description Base64 encoded audio data (WAV format) */
            audioData?: string;
            /**
             * Format: int32
             * @description Priority for audio playback (higher = higher priority)
             * @default 50
             */
            priority: number;
            /**
             * Format: date-time
             * @description Timestamp of the message
             */
            timestamp?: string;
            /** @description Tool name (for tool_use messages) */
            toolName?: string;
            /** @description Tool input (for tool_use messages) */
            toolInput?: {
                [key: string]: unknown;
            };
            /** @description Tool result output (for tool_result messages) */
            toolOutput?: string;
            /** @description Error details (for error messages) */
            error?: string;
            /** @description Content details (for content_block messages) */
            content?: string;
        };
        /**
         * @description Connection status for WebSocket
         * @enum {string}
         */
        ConnectionStatus: "connecting" | "connected" | "disconnected" | "error";
        /** @description Error response */
        ErrorResponse: {
            /** @description Error message */
            message: string;
        };
        /**
         * @description WebSocket message types
         * @enum {string}
         */
        MessageType: "user" | "assistant" | "system" | "audio" | "tool_use" | "tool_result" | "content_block" | "error";
        /** @description WebSocket status message */
        WebSocketStatus: {
            /** @description Current connection status */
            status: components["schemas"]["ConnectionStatus"];
            /** @description Optional error message */
            error?: string;
            /**
             * Format: date-time
             * @description Timestamp of status change
             */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Agents_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentListResponse"];
                };
            };
        };
    };
    Agents_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
