root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # セッションのプロジェクトとセッション名を環境変数から取得
  # 使用例: PROJECT=myproject SESSION=mysession air
  args_bin = ["--voice", "--ai", "--voice-speaker", "61", "--server"]
  bin = "./bin/claude-companion"
  cmd = "go build -o ./bin/claude-companion ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "web", "node_modules", ".scratch"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
