package event

import (
	"fmt"
	"sync"
	"time"

	"github.com/kazegusuri/claude-companion/internal/logger"
	"github.com/kazegusuri/claude-companion/internal/narrator"
	"github.com/kazegusuri/claude-companion/internal/server/handler"
)

// Handler is the central event handler that processes all events
type Handler struct {
	sessionManager *handler.SessionManager
	narrator       narrator.Narrator
	printer        Printer
	emitter        handler.MessageEmitter
	eventChan      chan Event
	wg             sync.WaitGroup
	done           chan struct{}
	mu             sync.RWMutex
	subscribers    map[Type][]func(Event)
}

// NewHandler creates a new central event handler
func NewHandler(sessionManager *handler.SessionManager, narrator narrator.Narrator, printer Printer, emitter handler.MessageEmitter) *Handler {
	return &Handler{
		sessionManager: sessionManager,
		narrator:       narrator,
		printer:        printer,
		emitter:        emitter,
		eventChan:      make(chan Event, 100),
		done:           make(chan struct{}),
		subscribers:    make(map[Type][]func(Event)),
	}
}

// Start begins processing events
func (h *Handler) Start() {
	h.wg.Add(1)
	go h.processEvents()
}

// Stop stops the event handler
func (h *Handler) Stop() {
	close(h.done)
	// Don't close eventChan here to prevent panic on send
	// The processEvents goroutine will exit when done is closed
	h.wg.Wait()
}

// SendEvent sends an event to be processed
func (h *Handler) SendEvent(event Event) {
	select {
	case <-h.done:
		// Handler is stopping, discard event
		return
	default:
		// Try to send event
		select {
		case h.eventChan <- event:
		case <-h.done:
			// Handler stopped while sending, discard event
		}
	}
}

// Subscribe adds a subscriber for a specific event type
func (h *Handler) Subscribe(eventType Type, handler func(Event)) {
	h.mu.Lock()
	defer h.mu.Unlock()
	h.subscribers[eventType] = append(h.subscribers[eventType], handler)
}

// processEvents processes events from the channel
func (h *Handler) processEvents() {
	defer h.wg.Done()

	for {
		select {
		case event, ok := <-h.eventChan:
			if !ok {
				return
			}
			h.processEvent(event)
		case <-h.done:
			// Drain remaining events
			for {
				select {
				case event, ok := <-h.eventChan:
					if !ok {
						return
					}
					h.processEvent(event)
				default:
					return
				}
			}
		}
	}
}

// processEvent processes a single event based on its type
func (h *Handler) processEvent(event Event) {
	eventType := event.Type()

	// Handle specific event types
	switch e := event.(type) {
	case *NotificationEvent:
		h.handleNotificationEvent(e)
	case *SystemMessage:
		h.handleSystemMessage(e)
	case *SummaryEvent:
		h.handleSummaryEvent(e)
	case *UserMessage:
		h.handleUserMessage(e)
	case *TaskCompletionMessage:
		h.handleTaskCompletionMessage(e)
	case *AssistantMessage:
		h.handleAssistantMessage(e)
	case *ResumeEvent:
		h.handleResumeEvent(e)
	default:
		logger.DebugWarning("Unknown event type in central handler: %T", event)
	}

	// Notify subscribers
	h.notifySubscribers(eventType, event)
}

// handleNotificationEvent processes notification events
func (h *Handler) handleNotificationEvent(event *NotificationEvent) {
	// Create session through SessionManager for SessionStart events
	if event.HookEventName == "SessionStart" {
		// CWD is not available in Session anymore, use empty string
		h.sessionManager.CreateSession(event.Session.SessionID, "", "", event.Session.TranscriptPath)
	}

	// Generate narration based on event type
	var narrationText string
	switch event.HookEventName {
	case "PreCompact":
		narrationText, _ = h.narrator.NarrateNotification(narrator.NotificationTypeCompact)

	case "SessionStart":
		// Determine notification type based on source
		var notificationType narrator.NotificationType
		switch event.Source {
		case "startup":
			notificationType = narrator.NotificationTypeSessionStartStartup
		case "clear":
			notificationType = narrator.NotificationTypeSessionStartClear
		case "resume":
			notificationType = narrator.NotificationTypeSessionStartResume
		default:
			notificationType = narrator.NotificationTypeSessionStartStartup
		}
		narrationText, _ = h.narrator.NarrateNotification(notificationType)

	case "Notification":
		// Handle based on message type
		switch msg := event.Message.(type) {
		case *NotificationPermissionMessage:
			// Tool permission request
			narrationText, _ = h.narrator.NarrateToolUsePermission(msg.ToolName)

			// Send tool permission to WebSocket
			if msg.ToolName != "" && h.emitter != nil {
				confirmMsg := &handler.ChatMessage{
					Type:      handler.MessageTypeSystem,
					Role:      handler.MessageRoleSystem,
					ID:        "", // Will be generated by the receiver if needed
					Text:      fmt.Sprintf("Tool permission requested: %s", msg.ToolName),
					Timestamp: time.Now(),
					Metadata: handler.Metadata{
						EventType: "tool_permission",
						ToolName:  msg.ToolName,
						SessionID: event.Session.SessionID,
					},
				}
				h.emitter.BroadcastChat(confirmMsg)
			}

		case *NotificationGeneralMessage:
			// General notification narration
			meta := &narrator.EventMeta{
				SessionID: event.Session.SessionID,
				CWD:       "", // CWD is not available in NotificationEvent
				Timestamp: time.Now(),
			}
			narrationText, _ = h.narrator.NarrateText(msg.Text, false, meta)

		default:
			// Fallback to raw message if no parsed content
			if event.RawMessage != "" {
				meta := &narrator.EventMeta{
					SessionID: event.Session.SessionID,
					CWD:       "", // CWD is not available in NotificationEvent
					Timestamp: time.Now(),
				}
				narrationText, _ = h.narrator.NarrateText(event.RawMessage, false, meta)
			}
		}
	}

	// Set narration if generated
	if narrationText != "" {
		event.Narration = &NarrationMessage{
			Text: narrationText,
		}
	}

	// Print the notification
	if h.printer != nil {
		h.printer.Print(event)
	}
}

// handleSystemMessage processes system message events
func (h *Handler) handleSystemMessage(event *SystemMessage) {
	// Set default content if not already set
	if event.Content == nil && event.RawContent != "" {
		event.Content = &DefaultSystemMessageContent{
			Text: event.RawContent,
		}
	}

	// Generate narration if needed
	if _, ok := event.Content.(*DefaultSystemMessageContent); ok && !event.IsMeta {
		meta := &narrator.EventMeta{
			SessionID: event.Session.SessionID,
			CWD:       event.CWD,
			Timestamp: event.Timestamp,
		}
		narrationText, _ := h.narrator.NarrateText(event.RawContent, false, meta)
		if narrationText != "" {
			event.Narration = &NarrationMessage{
				Text: narrationText,
			}
		}
	}

	// Send to WebSocket if not a meta message and not a hook event
	// Skip sending hook-related system messages (e.g., "SessionStart:clear")
	_, isHookMessage := event.Content.(*HookSystemMessageContent)
	if h.emitter != nil && !event.IsMeta && !isHookMessage {
		chatMsg := &handler.ChatMessage{
			Type:      handler.MessageTypeSystem,
			ID:        event.UUID,
			Role:      handler.MessageRoleSystem,
			Text:      event.RawContent,
			Priority:  1,
			Timestamp: event.Timestamp,
			Metadata: handler.Metadata{
				EventType: "system_message",
				SessionID: event.Session.SessionID,
				Role:      handler.MessageRoleSystem,
			},
		}
		h.emitter.BroadcastChat(chatMsg)
	}

	// Print the system message
	if h.printer != nil {
		h.printer.Print(event)
	}
}

// handleSummaryEvent processes summary events
func (h *Handler) handleSummaryEvent(event *SummaryEvent) {
	// do nothing
}

// handleUserMessage processes user message events
func (h *Handler) handleUserMessage(event *UserMessage) {
	// Send to WebSocket only if:
	// 1. Not a meta message
	// 2. Content is UserMessageContentMessage (not UserMessageContentList)
	if h.emitter != nil && !event.IsMeta {
		if msgContent, ok := event.Message.Content.(*UserMessageContentMessage); ok {
			chatMsg := &handler.ChatMessage{
				Type:      handler.MessageTypeUser,
				ID:        event.UUID,
				Role:      handler.MessageRoleUser,
				Text:      msgContent.Text,
				Priority:  1,
				Timestamp: event.Timestamp,
				Metadata: handler.Metadata{
					EventType: "user_message",
					SessionID: event.Session.SessionID,
					Role:      handler.MessageRoleUser,
				},
			}
			h.emitter.BroadcastChat(chatMsg)
		}
	}
}

// handleTaskCompletionMessage processes task completion messages
func (h *Handler) handleTaskCompletionMessage(event *TaskCompletionMessage) {
	// Generate narration for task completion
	meta := &narrator.EventMeta{
		SessionID: event.Session.SessionID,
		CWD:       "", // CWD is not available in TaskCompletionMessage
		Timestamp: event.Timestamp,
	}

	// Generate narration based on the task description and agent type
	var narrationText string
	if event.TaskInfo.SubagentType != "" {
		narrationText, _ = h.narrator.NarrateText(
			fmt.Sprintf("%s agentがタスク「%s」を完了しました",
				event.TaskInfo.SubagentType,
				event.TaskInfo.Description),
			false,
			meta,
		)
	} else {
		narrationText, _ = h.narrator.NarrateText(
			fmt.Sprintf("タスク「%s」を完了しました", event.TaskInfo.Description),
			false,
			meta,
		)
	}

	if narrationText != "" {
		event.Narration = &NarrationMessage{
			Text: narrationText,
		}
	}

	// Print the task completion
	if h.printer != nil {
		h.printer.Print(event)
	}
}

// handleResumeEvent processes resume events
func (h *Handler) handleResumeEvent(event *ResumeEvent) {
	// Print the resume event directly without narration
	if h.printer != nil {
		h.printer.Print(event)
	}
}

// handleAssistantMessage processes assistant messages
func (h *Handler) handleAssistantMessage(event *AssistantMessage) {
	// Generate narration based on content type
	switch content := event.Message.Content.(type) {
	case *APIErrorMessageContent:
		// Generate narration for API errors
		narrationText, _ := h.narrator.NarrateAPIError(
			content.StatusCode,
			content.ErrorType,
			content.Error.Message,
		)

		if narrationText != "" {
			event.Narration = &NarrationMessage{
				Text: narrationText,
			}
		}

	case *AssistantMessageContentText:
		// Generate narration for text content
		meta := &narrator.EventMeta{
			SessionID: event.Session.SessionID,
			CWD:       event.CWD,
			Timestamp: event.Timestamp,
		}

		// Use ProcessedText if available, otherwise use Text
		textToNarrate := content.ProcessedText
		if textToNarrate == "" {
			textToNarrate = content.Text
		}

		narrationText, _ := h.narrator.NarrateText(textToNarrate, content.IsThinking, meta)
		if narrationText != "" {
			content.Narration = &NarrationMessage{
				Text: narrationText,
			}
		}

	case *AssistantMessageContentList:
		// Generate narration for each text item in the list
		meta := &narrator.EventMeta{
			SessionID: event.Session.SessionID,
			CWD:       event.CWD,
			Timestamp: event.Timestamp,
		}

		for _, item := range content.Items {
			switch contentItem := item.(type) {
			case *AssistantMessageContentText:
				// Use ProcessedText if available, otherwise use Text
				textToNarrate := contentItem.ProcessedText
				if textToNarrate == "" {
					textToNarrate = contentItem.Text
				}

				narrationText, _ := h.narrator.NarrateText(textToNarrate, contentItem.IsThinking, meta)
				if narrationText != "" {
					contentItem.Narration = &NarrationMessage{
						Text: narrationText,
					}
				}
			case *AssistantMessageContentToolUse:
				// Generate narration for tool use
				inputMap := h.convertToolInputToMap(contentItem.Input)
				narrationText, _ := h.narrator.NarrateToolUse(contentItem.Name, inputMap)
				if narrationText != "" {
					contentItem.Narration = &NarrationMessage{
						Text: narrationText,
					}
				}
			}
		}
	}

	// Print the assistant message
	if h.printer != nil {
		h.printer.Print(event)
	}
}

// convertToolInputToMap converts tool input back to map for narrator
func (h *Handler) convertToolInputToMap(input AssistantMessageContentToolUseInput) map[string]interface{} {
	result := make(map[string]interface{})

	switch toolInput := input.(type) {
	case *ToolUseTodoWrite:
		todos := make([]map[string]interface{}, 0, len(toolInput.Todos))
		for _, todo := range toolInput.Todos {
			todoMap := map[string]interface{}{
				"content": todo.Content,
				"status":  todo.Status,
			}
			if todo.ActiveForm != "" {
				todoMap["activeForm"] = todo.ActiveForm
			}
			todos = append(todos, todoMap)
		}
		result["todos"] = todos

	case *ToolUseBash:
		result["command"] = toolInput.Command
		if toolInput.Description != "" {
			result["description"] = toolInput.Description
		}
		if toolInput.RunInBackground {
			result["run_in_background"] = toolInput.RunInBackground
		}
		if toolInput.Timeout > 0 {
			result["timeout"] = toolInput.Timeout
		}

	case *ToolUseRead:
		result["file_path"] = toolInput.FilePath
		if toolInput.Limit > 0 {
			result["limit"] = toolInput.Limit
		}
		if toolInput.Offset > 0 {
			result["offset"] = toolInput.Offset
		}

	case *ToolUseWrite:
		result["file_path"] = toolInput.FilePath
		result["content"] = toolInput.Content

	case *ToolUseEdit:
		result["file_path"] = toolInput.FilePath
		result["old_string"] = toolInput.OldString
		result["new_string"] = toolInput.NewString
		if toolInput.ReplaceAll {
			result["replace_all"] = toolInput.ReplaceAll
		}

	case *ToolUseMultiEdit:
		result["file_path"] = toolInput.FilePath
		edits := make([]map[string]interface{}, 0, len(toolInput.Edits))
		for _, edit := range toolInput.Edits {
			editMap := map[string]interface{}{
				"old_string": edit.OldString,
				"new_string": edit.NewString,
			}
			if edit.ReplaceAll {
				editMap["replace_all"] = edit.ReplaceAll
			}
			edits = append(edits, editMap)
		}
		result["edits"] = edits

	case *ToolUseGrep:
		result["pattern"] = toolInput.Pattern
		if toolInput.Path != "" {
			result["path"] = toolInput.Path
		}
		if toolInput.Glob != "" {
			result["glob"] = toolInput.Glob
		}
		if toolInput.Type != "" {
			result["type"] = toolInput.Type
		}
		if toolInput.OutputMode != "" {
			result["output_mode"] = toolInput.OutputMode
		}
		if toolInput.ContextAfter > 0 {
			result["-A"] = toolInput.ContextAfter
		}
		if toolInput.ContextBefore > 0 {
			result["-B"] = toolInput.ContextBefore
		}
		if toolInput.Context > 0 {
			result["-C"] = toolInput.Context
		}
		if toolInput.CaseInsensitive {
			result["-i"] = toolInput.CaseInsensitive
		}
		if toolInput.ShowLineNumbers {
			result["-n"] = toolInput.ShowLineNumbers
		}
		if toolInput.HeadLimit > 0 {
			result["head_limit"] = toolInput.HeadLimit
		}
		if toolInput.Multiline {
			result["multiline"] = toolInput.Multiline
		}

	case *ToolUseGlob:
		result["pattern"] = toolInput.Pattern
		if toolInput.Path != "" {
			result["path"] = toolInput.Path
		}

	case *ToolUseTask:
		result["description"] = toolInput.Description
		result["prompt"] = toolInput.Prompt
		result["subagent_type"] = toolInput.SubagentType

	case *ToolUseWebFetch:
		result["url"] = toolInput.URL
		result["prompt"] = toolInput.Prompt

	case *ToolUseWebSearch:
		result["query"] = toolInput.Query
		if len(toolInput.AllowedDomains) > 0 {
			result["allowed_domains"] = toolInput.AllowedDomains
		}
		if len(toolInput.BlockedDomains) > 0 {
			result["blocked_domains"] = toolInput.BlockedDomains
		}

	case *ToolUseNotebookEdit:
		result["notebook_path"] = toolInput.NotebookPath
		if toolInput.CellID != "" {
			result["cell_id"] = toolInput.CellID
		}
		if toolInput.CellType != "" {
			result["cell_type"] = toolInput.CellType
		}
		if toolInput.EditMode != "" {
			result["edit_mode"] = toolInput.EditMode
		}
		result["new_source"] = toolInput.NewSource

	case *ToolUseExitPlanMode:
		result["plan"] = toolInput.Plan

	case *ToolUseBashOutput:
		result["bash_id"] = toolInput.BashID
		if toolInput.Filter != "" {
			result["filter"] = toolInput.Filter
		}

	case *ToolUseKillBash:
		result["shell_id"] = toolInput.ShellID

	case *ToolUseMCP:
		// For MCP tools, return the data as-is
		result = toolInput.Data

	case *ToolUseGeneric:
		// For generic tools, return the data as-is
		result = toolInput.Data
	}

	return result
}

// notifySubscribers notifies all subscribers of an event type
func (h *Handler) notifySubscribers(eventType Type, event Event) {
	h.mu.RLock()
	subscribers := h.subscribers[eventType]
	h.mu.RUnlock()

	for _, subscriber := range subscribers {
		// Call subscriber in a goroutine to avoid blocking
		go func(handler func(Event)) {
			defer func() {
				if r := recover(); r != nil {
					logger.LogError("Subscriber panic: %v", r)
				}
			}()
			handler(event)
		}(subscriber)
	}
}
