// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// Agent Agent information representing a Claude agent process
type Agent struct {
	// CreatedAt Timestamp when the agent was created
	CreatedAt time.Time `json:"createdAt"`

	// Pid Process ID of the agent
	Pid int32 `json:"pid"`

	// ProjectDir Project directory path
	ProjectDir string `json:"projectDir"`

	// ProjectName Project name (extracted from projectDir)
	ProjectName string `json:"projectName"`

	// SessionId Session ID of the Claude session
	SessionId string `json:"sessionId"`

	// UpdatedAt Timestamp when the agent was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// AgentListResponse Response containing a list of agents
type AgentListResponse struct {
	// Agents List of active agents
	Agents []Agent `json:"agents"`
}

// ErrorResponse Error response
type ErrorResponse struct {
	// Message Error message
	Message string `json:"message"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/agents)
	AgentsList(ctx echo.Context) error

	// (GET /api/agents/{pid})
	AgentsRead(ctx echo.Context, pid int32) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// AgentsList converts echo context to params.
func (w *ServerInterfaceWrapper) AgentsList(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AgentsList(ctx)
	return err
}

// AgentsRead converts echo context to params.
func (w *ServerInterfaceWrapper) AgentsRead(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "pid" -------------
	var pid int32

	err = runtime.BindStyledParameterWithOptions("simple", "pid", ctx.Param("pid"), &pid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AgentsRead(ctx, pid)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/agents", wrapper.AgentsList)
	router.GET(baseURL+"/api/agents/:pid", wrapper.AgentsRead)

}

type AgentsListRequestObject struct {
}

type AgentsListResponseObject interface {
	VisitAgentsListResponse(w http.ResponseWriter) error
}

type AgentsList200JSONResponse AgentListResponse

func (response AgentsList200JSONResponse) VisitAgentsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AgentsReadRequestObject struct {
	Pid int32 `json:"pid"`
}

type AgentsReadResponseObject interface {
	VisitAgentsReadResponse(w http.ResponseWriter) error
}

type AgentsRead200JSONResponse Agent

func (response AgentsRead200JSONResponse) VisitAgentsReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AgentsRead404JSONResponse ErrorResponse

func (response AgentsRead404JSONResponse) VisitAgentsReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/agents)
	AgentsList(ctx context.Context, request AgentsListRequestObject) (AgentsListResponseObject, error)

	// (GET /api/agents/{pid})
	AgentsRead(ctx context.Context, request AgentsReadRequestObject) (AgentsReadResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// AgentsList operation middleware
func (sh *strictHandler) AgentsList(ctx echo.Context) error {
	var request AgentsListRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AgentsList(ctx.Request().Context(), request.(AgentsListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AgentsList")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AgentsListResponseObject); ok {
		return validResponse.VisitAgentsListResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AgentsRead operation middleware
func (sh *strictHandler) AgentsRead(ctx echo.Context, pid int32) error {
	var request AgentsReadRequestObject

	request.Pid = pid

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AgentsRead(ctx.Request().Context(), request.(AgentsReadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AgentsRead")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AgentsReadResponseObject); ok {
		return validResponse.VisitAgentsReadResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
