// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// Defines values for ToolStatus.
const (
	Created         ToolStatus = "created"
	Finished        ToolStatus = "finished"
	Running         ToolStatus = "running"
	WaitingApproval ToolStatus = "waiting_approval"
)

// Agent Agent information representing a Claude agent process
type Agent struct {
	// AgentType Type of the agent (e.g., "Claude Code")
	AgentType string `json:"agentType"`

	// CreatedAt Timestamp when the agent was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier (UUID) for the agent
	Id string `json:"id"`

	// Pid Process ID of the agent
	Pid int32 `json:"pid"`

	// ProjectDir Project directory path
	ProjectDir string `json:"projectDir"`

	// ProjectName Project name (extracted from projectDir)
	ProjectName string `json:"projectName"`

	// Session Session details
	Session *Session `json:"session,omitempty"`

	// SessionId Session ID of the Claude session
	SessionId string `json:"sessionId"`

	// UpdatedAt Timestamp when the agent was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// AgentListResponse Response containing a list of agents
type AgentListResponse struct {
	// Agents List of active agents
	Agents []Agent `json:"agents"`
}

// BackgroundTaskInfo Background task information
type BackgroundTaskInfo struct {
	// BackgroundTaskId Background task ID
	BackgroundTaskId string `json:"backgroundTaskId"`

	// Command Command being executed
	Command string `json:"command"`

	// CreatedAt Timestamp when the task was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Description of the task
	Description string `json:"description"`

	// IsTerminated Whether the task has been terminated
	IsTerminated bool `json:"isTerminated"`

	// TerminatedAt Timestamp when the task was terminated
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`

	// ToolUseId Tool use ID associated with this task
	ToolUseId string `json:"toolUseId"`
}

// ErrorResponse Error response
type ErrorResponse struct {
	// Message Error message
	Message string `json:"message"`
}

// Session Session information
type Session struct {
	// ActiveTool Active tool information
	ActiveTool *ToolInfo `json:"activeTool,omitempty"`

	// BackgroundTasks Background tasks
	BackgroundTasks *[]BackgroundTaskInfo `json:"backgroundTasks,omitempty"`

	// Cwd Current working directory
	Cwd string `json:"cwd"`

	// SessionId Session ID
	SessionId string `json:"sessionId"`

	// StartTime Timestamp when the session started
	StartTime time.Time `json:"startTime"`

	// TranscriptPath Path to the transcript file
	TranscriptPath string `json:"transcriptPath"`

	// Uuid UUID of the event that created this session
	Uuid string `json:"uuid"`
}

// ToolInfo Tool information
type ToolInfo struct {
	// CreatedAt Timestamp when the tool was created
	CreatedAt time.Time `json:"createdAt"`

	// IsError Whether the tool resulted in an error
	IsError bool `json:"isError"`

	// IsRejected Whether the tool was rejected
	IsRejected bool `json:"isRejected"`

	// IsWaitingApproval Whether the tool is waiting for approval
	IsWaitingApproval bool `json:"isWaitingApproval"`

	// Status Tool status
	Status ToolStatus `json:"status"`

	// ToolName Tool name
	ToolName string `json:"toolName"`

	// ToolUseId Tool use ID
	ToolUseId string `json:"toolUseId"`

	// UpdatedAt Timestamp when the tool was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// ToolStatus Tool execution status
type ToolStatus string

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/agents)
	AgentsList(ctx echo.Context) error

	// (GET /api/agents/{id})
	AgentsRead(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// AgentsList converts echo context to params.
func (w *ServerInterfaceWrapper) AgentsList(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AgentsList(ctx)
	return err
}

// AgentsRead converts echo context to params.
func (w *ServerInterfaceWrapper) AgentsRead(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AgentsRead(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/agents", wrapper.AgentsList)
	router.GET(baseURL+"/api/agents/:id", wrapper.AgentsRead)

}

type AgentsListRequestObject struct {
}

type AgentsListResponseObject interface {
	VisitAgentsListResponse(w http.ResponseWriter) error
}

type AgentsList200JSONResponse AgentListResponse

func (response AgentsList200JSONResponse) VisitAgentsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AgentsReadRequestObject struct {
	Id string `json:"id"`
}

type AgentsReadResponseObject interface {
	VisitAgentsReadResponse(w http.ResponseWriter) error
}

type AgentsRead200JSONResponse Agent

func (response AgentsRead200JSONResponse) VisitAgentsReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AgentsRead404JSONResponse ErrorResponse

func (response AgentsRead404JSONResponse) VisitAgentsReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/agents)
	AgentsList(ctx context.Context, request AgentsListRequestObject) (AgentsListResponseObject, error)

	// (GET /api/agents/{id})
	AgentsRead(ctx context.Context, request AgentsReadRequestObject) (AgentsReadResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// AgentsList operation middleware
func (sh *strictHandler) AgentsList(ctx echo.Context) error {
	var request AgentsListRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AgentsList(ctx.Request().Context(), request.(AgentsListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AgentsList")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AgentsListResponseObject); ok {
		return validResponse.VisitAgentsListResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AgentsRead operation middleware
func (sh *strictHandler) AgentsRead(ctx echo.Context, id string) error {
	var request AgentsReadRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AgentsRead(ctx.Request().Context(), request.(AgentsReadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AgentsRead")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AgentsReadResponseObject); ok {
		return validResponse.VisitAgentsReadResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
